name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: |
        gcc -o GetTaskID_T1 GetTaskID_T1.c Sources/APIs_Sources/Tasks.c -I Headers/APIs_Headers/Tasks.h
    - name: test
      run: |
        ./GetTaskID_T1
        if [ "$?" -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi

