name: Doxygen

on: [push]
#   push:
#     branches:
#       - main

jobs:
  build:
    name: Doxygen
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
            # Set always-auth in npmrc
            always-auth: FALSE
            # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
            node-version: 16.x
            # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version
            node-version-file: .node-version
            # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
            architecture: x64
            # Set this option if you want the action to check for the latest available version that satisfies the version spec
            check-latest: TRUE
            # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
            registry-url: FALSE
            # Used to pull node distributions from node-versions.  Since there's a default, this is typically not supplied by the user.
            token: ${{ github.token }}
            # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
            cache: npm
            # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
            cache-dependency-path: .json

      
      - name: Checkout code & Set up Node.js 16
        uses: actions/setup-node@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate documentation
        run: doxygen Doxyfile
