name: Doxygen

on: [push]
#   push:
#     branches:
#       - main

jobs:
  build:
    name: Doxygen
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install
      env:
        CI: true
        
    - name: Install Doxygen
      run: |
        sudo apt-get update && sudo apt-get install -y doxygen
        doxygen --version

    - name: Generate documentation
      run: |
        doxygen Doxyfile
        #doxygen -g Doxyfile
