name: MISRA-C
on: [push]

jobs:
  build:
    name: Misra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          other_options: --addon=misra.py
          output_file: Misra_Violations.txt
          exclude_check: ./Tests
      - name: Generate Misra-Violations.txt
        run: |
          cp Misra_Violations.txt $GITHUB_WORKSPACE/Generated_Misra_Violations.txt
      - name: Commit and push Misra-Violations.txt
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Generated_Misra_Violations.txt
          git commit -m "Add Generated_Misra_Violations.txt"
          git push --force origin ${{ github.ref }}
