name: MISRA-C
on: [push]

jobs:
  build:
    name: Misra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          other_options: --addon=misra.py --rule-texts=misra_rules.txt
          output_file: Misra_Violations.txt
          exclude_check: ./Tests
      - name: Create MISRA folder
        run: |
          mkdir -p Tests/MISRA
      - name: Move Misra-Violations.txt to /Tests/MISRA
        run: |
          mv Misra_Violations.txt Tests/MISRA/
      - name: Commit and push Misra-Violations.txt
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Tests/MISRA/Misra_Violations.txt
          git commit -m "Add Misra_Violations.txt to /Tests/MISRA folder"
          git push origin ${{ github.ref }}
